<?php
$links='{"links":[  
		{"img":"krakow_150.png",
         "ttl":"Akademia Muzyczna, Krakow",
		 "href":"https://www.amuz.krakow.pl"},
	     {"img":"alexandertechnique_150.jpg",
		 "ttl":"Alexander Technique",
		 "href":"http://www.alexandertechnique.com/"},
		 {"img":"wikipedia.png",
		 "ttl":"Alexander Technique<br/>(Wikipedia)",
		 "href":"https://en.wikipedia.org/wiki/Alexander_Technique"},
		 {"img":"abrsm1.jpg",
		 "ttl":"Associated Board of the Royal Schools of Music (ABRSM)",
		 "href":"http://de.abrsm.org/en/home"},
		 {"img":"elztalmuseum_150.jpg",
		 "ttl":"Elztal Museum",
		 "href":"http://www.elztalmuseum.de"},
		 {"img":"epta_150.png",
		 "ttl":"European Piano Teachers Association (EPTA)",
		 "href":"https://epta-uk.org"},
		 {"img":"blidos.jpg",
		 "ttl":"Fedra + Stefan Blido",
		 "href":"http://www.blido.de"},
		 {"img":"Ina_Birk_150.jpg",
		 "ttl":"<br/>Ina Birk",
		 "href":"http://www.ina-birk-klavier.de"},
		 {"img":"klappe11_150.jpg",
		 "ttl":"Klappe 11 Festival",
		 "href":"http://www.klappe11.de"},
		{"img":"pf_150.png",
		 "ttl":"Peter Feuchtwanger - Pianist, Composer, Padagogue",
		 "href":"http://www.peter-feuchtwanger.de/english-version/index.html"},
		 {"img":"pfclub_150.jpg", 
		 "ttl":"Peter Feuchtwanger Club<br/>(Facebook)",
		 "href":"https://www.facebook.com/Peter-Feuchtwanger-Club-195576167160189"},
		 {"img":"wikipedia.png",
		 "ttl":"Peter Feuchtwanger<br/>(Wikipedia)",
		 "href":"https://en.wikipedia.org/wiki/Peter_Feuchtwanger"},
		 {"img":"ram.png",
		 "ttl":"Royal Academy of Music (RAM)",	 
		 "href":"http://www.ram.ac.uk"},
		 {"img":"robert_150.jpg",
		 "ttl":"Robbert Van Steijn",
		 "href":"http://www.robbertvansteijn.net/"},
		 {"img":"vetter_150.jpg",
		 "ttl":"Sophie Mayuko Vetter",
		 "href":"http://sophie-mayuko-vetter.com"},		 
		 {"img":"waldkirch150.png",
		 "ttl":"Waldkirch",
		 "href":"http://www.stadt-waldkirch.de"},
		 {"img":"wms_150.png",
		 "ttl":"Waldkirch Music School",
		 "href":"http://www.fv-musikschule-waldkirch.de"},
		 {"img":"orgel_150.jpg",
		 "ttl":"Waldkirch Orgelstiftung",
		 "href":"http://www.waldkircher-orgelstiftung.de"},
 		 {"img":"fb150.jpg",
		 "ttl":"William Cuthbertson<br/>(Facebook)",
		 "href":"https://www.facebook.com/william.cuthbertson.12"},
		 {"img":"linkedin_150.png",
		 "ttl":"William Cuthbertson<br/>(Linked In)",
		 "href":"https://www.linkedin.com/in/william-cuthbertson-36462453/"}
		 ]}'; 