<?php 
$gpics ='{"gallery":[';
$gpics.=' {"flag":"T","picTtl":"Meisterkurs 2017"},	
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"lesson.jpg","picSmall":"lesson_120.jpg","picTtl":"William Cuthbertson mit Student"},
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"lesson10.jpg","picSmall":"lesson10_120.jpg","picTtl":"William Cuthbertson mit Student"},
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"lesson2.jpg","picSmall":"lesson2_120.jpg","picTtl":"Manfred Seewan mit Student"},
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"lesson3.jpg","picSmall":"lesson3_120.jpg","picTtl":"Manfred Seewan mit Studenten"},
{"flag":"P"			
,"grpTtl":"Meisterkurs:2017","picLarge":"lesson4.jpg","picSmall":"lesson4_120.jpg","picTtl":"Manfred Seewan mit Studenten"},
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"lesson5.jpg","picSmall":"lesson5_120.jpg",
"picTtl":"Unterricht"}, 
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"lesson9.jpg","picSmall":"lesson9_120.jpg",
"picTtl":"Martina Barufke zeigt wie man korrekt sitzt"},
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"2017mcp2.jpg","picSmall":"2017mcp2_120.jpg",
"picTtl":"Abschlusskonzert"},
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"2017mcp3.jpg","picSmall":"2017mcp3_120.jpg",
"picTtl":"Abschlusskonzert"},
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"2017mcp4.jpg","picSmall":"2017mcp4_120.jpg",
"picTtl":"Abschlusskonzert"},
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"2017mcp6.jpg","picSmall":"2017mcp6_120.jpg",
"picTtl":"Ekaterine Khvedelidze am Meisterkurs Konzert"},
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"2017mcp5.jpg","picSmall":"2017mcp5_120.jpg",
"picTtl":"William Cuthbertson am Meisterkurs Konzert"},
{"flag":"P","grpTtl":"Meisterkurs:2017","picLarge":"2017mcp7.jpg","picSmall":"2017mcp7_120.jpg",
"picTtl":"Life Kinetik"},';

$gpics.='{"flag":"T","picTtl":"Peter Feuchtwanger Symposium 2017"},	
{"flag":"P","grpTtl":"Peter Feuchtwanger Symposium 2017", "picLarge":"feuchtwangermeeting2017-1.jpg", "picSmall":"feuchtwangermeeting2017-1_120.jpg","picTtl":""},
{"flag":"P","grpTtl":"Peter Feuchtwanger Symposium 2017", "picLarge":"feuchtwangermeeting2017-2.jpg","picSmall":"feuchtwangermeeting2017-2_120.jpg","picTtl":"Mayuko Vetter"},
{"flag":"P","grpTtl":"Peter Feuchtwanger Symposium 2017", "picLarge":"feuchtwangermeeting2017-3.jpg","picSmall":"feuchtwangermeeting2017-3_120.jpg","picTtl":"Daniel Kasparian"},
{"flag":"P","grpTtl":"Peter Feuchtwanger Symposium 2017", "picLarge":"feuchtwangermeeting2017-4.jpg","picSmall":"feuchtwangermeeting2017-4_120.jpg","picTtl":"Paul Weeren "},
{"flag":"P","grpTtl":"Peter Feuchtwanger Symposium 2017", "picLarge":"feuchtwangermeeting2017-5.jpg","picSmall":"feuchtwangermeeting2017-5_120.jpg","picTtl":"Ina Birk"},
{"flag":"T","picTtl":"Konzerte 2017"},	
{"flag":"P","grpTtl":"Konzerte 2017", "picLarge":"klappe112017.jpg", "picSmall":"klappe112017_120.jpg","picTtl":"William Cuthbertson am Klavier und Hermann Wernet am Bass/Klappe11","cpy":"Foto:Badische Zeitung"},
{"flag":"P","grpTtl":"Konzerte 2017", "picLarge":"KonzertJul17.jpg", "picSmall":"KonzertJul17_120.jpg","picTtl":"William Cuthbertson","cpy":"Foto:Badische Zeitung/Regina Lorenz"},
{"flag":"P","grpTtl":"Konzerte 2017","picLarge":"williamcuthbertsonemmastratton2017.jpg", "picSmall":"williamcuthbertsonemmastratton2017_120.jpg",
"picTtl":"William Cuthbertson+Emma Stratton "},
{"flag":"P","grpTtl":"Konzerte 2017","picLarge":"2017violinpiano.JPG", "picSmall":"2017violinpiano_120.JPG",
"picTtl":"William Cuthbertson mit Ivetta Viatet (Russland), Violin"},
{"flag":"T","picTtl":"Meisterkurse 2016"},	
{"flag":"P","grpTtl":"Meisterkurse:2016","picLarge":"17thmasterclass_1.jpg","picSmall":"17thmasterclass_1_120.jpg","picTtl":"William Cuthbertson mit Student, Emma Stratton","cpy":"Foto:Sanja Stefanovic"},
{"flag":"P","grpTtl":"Meisterkurse:2016","picLarge":"17thmasterclass_2.jpg","picSmall":"17thmasterclass_2_120.jpg","picTtl":"William Cuthbertson mit Studenten","cpy":"Sanja Stefanovic"},
{"flag":"P","grpTtl":"Meisterkurse:2016","picLarge":"17thmasterclass_3.jpg","picSmall":"17thmasterclass_3_120.jpg","picTtl":"William Cuthbertson mit Studenten","cpy":"Foto:Sanja Stefanovic"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"emmastratton.png","picSmall":"emmastratton_120.png","picTtl":"Peter Feuchtwanger Meisterkurs, Waldkirch - Emma Stratton - Andaluza and Allegro de Concerto by E.Granados."},';
$gpics.='{"flag":"T","picTtl":"Konzerte 2016"},
{"flag":"P","grpTtl":"Konzerte 2016","picLarge":"2006_1.jpg","picSmall":"2006_1_120.jpg","picTtl":"Stiftung Beatus, Sigriswil, Schweiz"},
{"flag":"P","grpTtl":"Konzerte 2016","picLarge":"novgorod1.png","picSmall":"novgorod1_tn.png","picTtl":"Novgorod,Russland"},
{"flag":"P","grpTtl":"Konzerte 2016","picLarge":"Fr08Juli2016.jpg","picSmall":"Fr08Juli2016_tn.jpg","picTtl":"Elztal Museum Concert","cpy":"Foto: Badische Zeitung, G. Zahn"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"tanzrhymiker.png","picSmall":"tanzrhymiker_120.png","picTtl":"Tanzrhythmiker, Waldkirch"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"masterclass2016concert.jpg","picSmall":"masterclass2016concert_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - William Cuthbertson - César Cui,Causerie"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_1.jpg","picSmall":"memorial2016_1_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Agnes Joshi - Franz Schubert, Walzer Nr.1 (1823), Nr.2 Ländler Nr.3,4,Jean Sibelius, Die Tanne Op.75 Nr.5"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_2.jpg","picSmall":"memorial2016_2_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Daniel Kasparian - J.S. Bach, Andante aus dem Klavierkonzert in f-Moll, Friedrich Kuhlau, Rondo C-Dur über Motive aus Mozarts Don Giovanni"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_3.jpg","picSmall":"memorial2016_3_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Masako Kamikawa - Peter Feuchtwanger, Study in the Eastern Idiom (Macedonian and Bosnian)"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_4.jpg","picSmall":"memorial2016_4_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Anne Roth - Elisabeth Jaquet de La Guerre Prelude-Allemande-Menuet-Gavotte aus der Suite A-Moll "},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_5.jpg","picSmall":"memorial2016_5_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Manfred Seeween - Felix Mendelssohn Bartholdy Fantasie fis-Moll Con motto Agitato, Allegro con Moto, Presto"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_6.jpg","picSmall":"memorial2016_6_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Ina Birk - Soniyage"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_7.jpg","picSmall":"memorial2016_7_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Marianne Schr&ouml;der"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_8.jpg","picSmall":"memorial2016_8_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Nina Attorf - Frederik Chopin, Nocturne cis-Moll"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_9.jpg","picSmall":"memorial2016_9_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Fedra und Stefan Blido - Louis Moreau Gottschalk, La Gallina, Ojos Criollos, Dance Cubaine"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_10.jpg","picSmall":"memorial2016_10_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Klaus Cutik - Serge Bortkiewicz, Etüde Des-dur Nr.8"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_11.jpg","picSmall":"memorial2016_11_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Sanja Stefanovic + Sophia Grech - Franz Liszt, Freudvoll und Leidvoll"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_13.jpg","picSmall":"memorial2016_13_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Alexander Reitenbach"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_14.jpg","picSmall":"memorial2016_14_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Jean-Jacques Dunki - Ludwig van Beethoven, 6 Bagatellen Op.126, Nr.1,2,3"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_15.jpg","picSmall":"memorial2016_15_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Paul Cibis und Mayuko Vetter - Franz Schubert, Polonaisen Nr.1,2 "},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_16.jpg","picSmall":"memorial2016_16_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Saeko Saito"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_17.jpg","picSmall":"memorial2016_17_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Andrew Kraus - Adolph von Henselt, Wiegenlied, Franz Schubert, arr.Leopold Godowsky, Wiegenlied, David Saperton, Zephyr"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"memorial2016_18.jpg","picSmall":"memorial2016_18_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Jorrit van den Ham - Franz Liszt, Consolation Nr.3 in Des Dur, L. M. Gottschalk, Souvenirs dAndalousie"},';
$gpics.='{"flag":"T","picTtl":"Konzerte 2015"},	
{"flag":"P","grpTtl":"Konzerte 2015","picLarge":"21april2015.jpg","picSmall":"21april2015_120.jpg","picTtl":"Preludes%20by%20Chopin%20and%20Scriabin","cpy":"Photo%20Badischer%20Zeitung"},		
{"flag":"P","grpTtl":"Konzerte 2015","picLarge":"bz2015-1.jpg","picSmall":"bz2015-1-120.jpg","picTtl":"Benefizkonzert mit Klassik und Chansons zugunsten der Renovierung des Gemeindezentrums","cpy":"Foto Badischer Zeitung"}';  
$gpics.=',{"flag":"T","picTtl":"Meisterkurs 2015"},
{"flag":"P","grpTtl":"Meisterkurse 2015", "picLarge":"masterclass2015_1.jpg","picSmall":"masterclass2015_1_tn.jpg","picTtl":"William mit Student"},
{"flag":"P","grpTtl":"Meisterkurse 2015","picLarge":"masterclass2015_2.jpg","picSmall":"masterclass2015_2_tn.jpg","picTtl":"William mit Studenten"},	
{"flag":"P","grpTtl":"Meisterkurse 2015", "picLarge":"masterclass2015_3.jpg","picSmall":"masterclass2015_3_tn.jpg","picTtl":"William mit Student"},	
{"flag":"P","grpTtl":"Meisterkurse 2015", "picLarge":"masterclass2015_4.jpg","picSmall":"masterclass2015_4_tn.jpg","picTtl":"William mit Student"},	
{"flag":"P","grpTtl":"Meisterkurse 2015","picLarge":"masterclass2015_5.png","picSmall":"masterclass2015_5_tn.png","picTtl":"Studenten"},	
{"flag":"P","grpTtl":"Meisterkurse 2015","picLarge":"masterclass2015_6.png","picSmall":"masterclass2015_6_tn.png","picTtl":"Student"},	
{"flag":"P","grpTtl":"Meisterkurse 2015","picLarge":"masterclass2015_11.jpg","picSmall":"masterclass2015_11_tn.jpg","picTtl":"After Party"},	
{"flag":"P","grpTtl":"Meisterkurse 2015",  "picLarge":"masterclass2015_7.jpg", "picSmall":"masterclass2015_7_tn.jpg","picTtl":"Abschlusskonzert. TeilnehmerInnen kriegen Blumen"},	
{"flag":"P","grpTtl":"Meisterkurse 2015", "picLarge":"masterclass2015_8.jpg","picSmall":"masterclass2015_8_tn.jpg","picTtl":"Stefan Blido (Feuchtwanger Übungen)"},
{"flag":"P","grpTtl":"Meisterkurse 2015", "picLarge":"masterclass2015_9.jpg","picSmall":"masterclass2015_9_tn.jpg","picTtl":"Und wir kriegen ein nettes Geschenk. William Cuthbertson (Klavier)"},
{"flag":"P","grpTtl":"Meisterkurse 2015", "picLarge":"masterclass2015_10.jpg","picSmall":"masterclass2015_10_tn.jpg","picTtl":"Martina Barufke (Alexander Technik)"}';
$gpics.=',{"flag":"T","picTtl":"Unterricht 2015"}
,{"flag":"P","grpTtl":"Unterricht 2015","picLarge":"Vorspiel1.jpg","picSmall":"Vorspiel1_tn.jpg","picTtl":"Klavier Schüler"}
,{"flag":"P","grpTtl":"Unterricht 2015","picLarge":"Vorspiel2.jpg","picSmall":"Vorspiel2_tn.jpg","picTtl":"Klavier und Violin Schüler"},
{"flag":"P","grpTtl":"Unterricht 2015","picLarge":"Vorspiel3.jpg","picSmall":"Vorspiel3_tn.jpg","picTtl":"Klavierschüler"},
{"flag":"P","grpTtl":"Unterricht 2015","picLarge":"Abrsm1-1.jpg","picSmall":"Abrsm1-1_tn.jpg",	"picTtl":"Klavierschülerin mit Zertifikat"},
{"flag":"P","grpTtl":"Unterricht:2015","picLarge":"Alban6.JPG","picSmall":"Alban6_240.JPG","picTtl":"William%20Cuthbertson (Klavier) mit Alban (French Horn)"}';
$gpics.=',{"flag":"T","picTtl":"Meisterkurse 2014"},
{"flag":"P","grpTtl":"Meisterkurse 2014","picLarge":"foto1.JPG","picSmall":"foto1_tn.jpg","picTtl":"Peter Feuchtwanger,William Cuthbetson mit Studenten"},
{"flag":"P","grpTtl":"Meisterkurse 2014","picLarge":"foto2.JPG","picSmall":"foto2_tn.jpg","picTtl":"Peter Feuchtwanger,William Cuthbetson mit Student"},
{"flag":"P", "grpTtl":"Meisterkurse 2014","picLarge":"foto3.JPG","picSmall":"foto3_tn.jpg","picTtl":"William Cuthbetson mit Studenten"},
{"flag":"P","grpTtl":"Meisterkurse 2014","picLarge":"foto4.JPG","picSmall":"foto4_tn.jpg","picTtl":"Peter Feuchtwanger mit Student"},
{"flag":"P","grpTtl":"Meisterkurse 2014","picLarge":"foto5.JPG","picSmall":"foto5_tn.jpg","picTtl":"Peter Feuchtwanger,William Cuthbetson mit Studenten"},
{"flag":"P","grpTtl":"Meisterkurse 2014","picLarge":"foto6.JPG","picSmall":"foto6_tn.jpg","picTtl":"Peter Feuchtwanger,William Cuthbertson und Student"},
{"flag":"P","grpTtl":"Meisterkurse 2014","picLarge":"foto7.JPG","picSmall":"foto7_tn.jpg","picTtl":"William Cuthbetson mit Studenten"},
{"flag":"P","grpTtl":"Meisterkurse 2014","picLarge":"foto8.JPG","picSmall":"foto8_tn.jpg","picTtl":"William Cuthbertson"},
{"flag":"P","grpTtl":"Meisterkurse 2014","picLarge":"peterfeutchtwangerKaoruMaruyamawilliam.jpg","picSmall":"peterfeutchtwangerKaoruMaruyamawilliam_tn.jpg","picTtl":"Peter Feutchtwanger,Kaoru Maruyama und William Cuthbertson"}';
$gpics.=',{"flag":"T","picTtl":"Konzerte 2014"},
{"flag":"P","grpTtl":"Konzerte 2014","picLarge":"kulturwoche2014.jpg","picSmall":"kulturwoche2014_120.jpg","picTtl":"Waldkircher kulturwoche 2014","cpy":"Photo Badische Zeitung"},
{"flag":"P","grpTtl":"Konzerte 2014","picLarge":"foto9.jpg","picSmall":"foto9_120.jpg","picTtl":"Waldkircher Musiker singen und spielen Musik von Mozart bis Bob Dylan"},
{"flag":"P","grpTtl":"Konzerte 2014","picLarge":"foto10.jpg","picSmall":"foto10_120.jpg","picTtl":"William Cuthbertson und Weimo Gao"},
{"flag":"P","grpTtl":"Konzerte 2014","picLarge":"foto12.jpg","picSmall":"foto12_120.jpg","picTtl":"Open Air Konzert mit den Waldkircher Tanzrhythmiker"},	
{"flag":"P","grpTtl":"Konzerte 2014","picLarge":"22october2014.jpg","picSmall":"22october2014_120.jpg","picTtl":"William Cuthbertson mit Sänger"},
{"flag":"P","grpTtl":"Konzerte 2014","picLarge":"chopin.jpg","picSmall":"chopin_120.jpg", "picTtl":"Chopin%20Konzert"},
{"flag":"P","grpTtl":"Konzerte 2014","picLarge":"concert_fb.jpg", "picSmall":"concert_fb_120.jpg","picTtl":"Konzert%20mit%20Weimo%20Gao"},
{"flag":"P","grpTtl":"Konzerte 2014","picLarge":"chopinetuden.jpg","picSmall":"chopinetuden_120.jpg","picTtl":"Chopin Etuden","cpy":"Foto Badische Zeitung"},
{"flag":"P","grpTtl":"Konzerte 2014","picLarge":"william2014.png","picSmall":"william2014_120.png","picTtl":"Elztal Museum Konzert"},';

$gpics.='{"flag":"T","picTtl":"Meisterkurs 2013"},	
{"flag":"P","grpTtl":"Meisterkurs:2013","picLarge":"14thMasterclass.jpg","picSmall":"14thMasterclass_120.jpg","picTtl":"Daniel Kasparian, Agnes Joshi-Meili, Elisa Neugart, Professor Peter Feuchtwanger, Masako Kamikawa, Urs Weilenmann und Christian Loeschke","cpy":"Foto: Badische Zeitung, Eberhard Weiss"},
{"flag":"P","grpTtl":"Meisterkurs:2013","picLarge":"14thMasterclass-2.jpg","picSmall":"14thMasterclass-2_120.jpg","picTtl":"Masako Kamikawa spielte Chopins Rondo in Es-Dur","cpy":"Foto: Badische Zeitung, Eberhard Weiss"}';
$gpics.=',{"flag":"T","picTtl":"Konzerte 2013"},
{"flag":"P","grpTtl":"Konzerte 2013","picLarge":"foto11.jpg","picSmall":"foto11_120.jpg","picTtl":"Gedichte von Wilhelm Busch, Musik von William Cuthbertson"}';

$gpics.=',{"flag":"T","picTtl":"Konzerte 2012"},
{"flag":"P","grpTtl":"Konzerte 2012","picLarge":"IMG_2402.JPG", "picSmall":"IMG_2402_120.jpg", "picTtl":"Nov.26th%202012%20in%20St.%20James,%20Piccadilly,%20London,%20England,%20wo%20William%20spielte%20Beethovens%20Hammerklavier-Sonate"},		
{"flag":"P","grpTtl":"Konzerte  2012","picLarge":"WilhelmBuschAbend.jpg","picSmall":"WilhelmBuschAbend_120.jpg","picTtl":"Wilhelm Busch Abend"},
{"flag":"P","grpTtl":"Concert 2012","picLarge":"yikisun.jpg","picSmall":"yikisun_120.jpg","picTtl":"Concert mit Sun Yiqi and William Cuthbertson"},
{"flag":"P","grpTtl":"Konzerte 2012","picLarge":"Gershwin2.JPG","picSmall":"Gershwin2_120.JPG","picTtl":"Rhapsody in Blue"},
{"flag":"P","grpTtl":"Konzerte 2012","picLarge":"NeuesBild.JPG","picSmall":"NeuesBild_120.JPG","picTtl":"Rhapsody in Blue"},
{"flag":"P","grpTtl":"Konzerte 2012","picLarge":"williamcuthbertsonfionamiddleton2012.jpg",
"picSmall":"williamcuthbertsonfionamiddleton2012_120.jpg","picTtl":"William Cuthbertson Fiona Middleton,Waldkircher Kulturwochen, photo:Hildegard Karig/Badische Zeitung"}';
$gpics.=']}';
?>